// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveAccount = `-- name: ArchiveAccount :exec
UPDATE accounts
SET is_archived = TRUE, updated_at = now()
WHERE id = $1 AND family_id = $2
`

type ArchiveAccountParams struct {
	ID       uuid.UUID
	FamilyID uuid.UUID
}

func (q *Queries) ArchiveAccount(ctx context.Context, arg ArchiveAccountParams) error {
	_, err := q.db.Exec(ctx, archiveAccount, arg.ID, arg.FamilyID)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    family_id, owner_user_id, name, kind, visibility, currency, initial_balance_cents, current_balance_cents, color
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, family_id, owner_user_id, name, kind, visibility, currency, initial_balance_cents, current_balance_cents, color, is_archived, created_at, updated_at
`

type CreateAccountParams struct {
	FamilyID            uuid.UUID
	OwnerUserID         uuid.UUID
	Name                string
	Kind                string
	Visibility          string
	Currency            string
	InitialBalanceCents int64
	CurrentBalanceCents int64
	Color               *string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.FamilyID,
		arg.OwnerUserID,
		arg.Name,
		arg.Kind,
		arg.Visibility,
		arg.Currency,
		arg.InitialBalanceCents,
		arg.CurrentBalanceCents,
		arg.Color,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.OwnerUserID,
		&i.Name,
		&i.Kind,
		&i.Visibility,
		&i.Currency,
		&i.InitialBalanceCents,
		&i.CurrentBalanceCents,
		&i.Color,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, family_id, owner_user_id, name, kind, visibility, currency, initial_balance_cents, current_balance_cents, color, is_archived, created_at, updated_at FROM accounts
WHERE id = $1 AND family_id = $2
`

type GetAccountByIDParams struct {
	ID       uuid.UUID
	FamilyID uuid.UUID
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, arg.ID, arg.FamilyID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.OwnerUserID,
		&i.Name,
		&i.Kind,
		&i.Visibility,
		&i.Currency,
		&i.InitialBalanceCents,
		&i.CurrentBalanceCents,
		&i.Color,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByFamilyID = `-- name: ListAccountsByFamilyID :many
SELECT a.id, a.family_id, a.owner_user_id, a.name, a.kind, a.visibility, a.currency, a.initial_balance_cents, a.current_balance_cents, a.color, a.is_archived, a.created_at, a.updated_at, u.full_name as owner_name
FROM accounts a
JOIN users u ON u.id = a.owner_user_id
WHERE a.family_id = $1 AND a.is_archived = FALSE
ORDER BY a.name ASC
`

type ListAccountsByFamilyIDRow struct {
	ID                  uuid.UUID
	FamilyID            uuid.UUID
	OwnerUserID         uuid.UUID
	Name                string
	Kind                string
	Visibility          string
	Currency            string
	InitialBalanceCents int64
	CurrentBalanceCents int64
	Color               *string
	IsArchived          bool
	CreatedAt           time.Time
	UpdatedAt           time.Time
	OwnerName           string
}

func (q *Queries) ListAccountsByFamilyID(ctx context.Context, familyID uuid.UUID) ([]ListAccountsByFamilyIDRow, error) {
	rows, err := q.db.Query(ctx, listAccountsByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsByFamilyIDRow{}
	for rows.Next() {
		var i ListAccountsByFamilyIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.OwnerUserID,
			&i.Name,
			&i.Kind,
			&i.Visibility,
			&i.Currency,
			&i.InitialBalanceCents,
			&i.CurrentBalanceCents,
			&i.Color,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET current_balance_cents = current_balance_cents + $3,
    updated_at = now()
WHERE id = $1 AND family_id = $2
RETURNING id, family_id, owner_user_id, name, kind, visibility, currency, initial_balance_cents, current_balance_cents, color, is_archived, created_at, updated_at
`

type UpdateAccountBalanceParams struct {
	ID                  uuid.UUID
	FamilyID            uuid.UUID
	CurrentBalanceCents int64
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.FamilyID, arg.CurrentBalanceCents)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.OwnerUserID,
		&i.Name,
		&i.Kind,
		&i.Visibility,
		&i.Currency,
		&i.InitialBalanceCents,
		&i.CurrentBalanceCents,
		&i.Color,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
