// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAIConversation = `-- name: CreateAIConversation :one
INSERT INTO ai_conversations (
    family_id, user_id, title
) VALUES (
    $1, $2, $3
)
RETURNING id, family_id, user_id, title, created_at, updated_at
`

type CreateAIConversationParams struct {
	FamilyID uuid.UUID
	UserID   uuid.UUID
	Title    string
}

func (q *Queries) CreateAIConversation(ctx context.Context, arg CreateAIConversationParams) (AiConversation, error) {
	row := q.db.QueryRow(ctx, createAIConversation, arg.FamilyID, arg.UserID, arg.Title)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAIMessage = `-- name: CreateAIMessage :one
INSERT INTO ai_messages (
    conversation_id, role, content, tool_calls, tool_call_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, conversation_id, role, content, tool_calls, tool_call_id, created_at
`

type CreateAIMessageParams struct {
	ConversationID uuid.UUID
	Role           string
	Content        *string
	ToolCalls      []byte
	ToolCallID     *string
}

func (q *Queries) CreateAIMessage(ctx context.Context, arg CreateAIMessageParams) (AiMessage, error) {
	row := q.db.QueryRow(ctx, createAIMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ToolCallID,
	)
	var i AiMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.CreatedAt,
	)
	return i, err
}

const createAIToolExecution = `-- name: CreateAIToolExecution :one
INSERT INTO ai_tool_executions (
    conversation_id, family_id, user_id, tool_name, parameters, status, approval_token
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, conversation_id, family_id, user_id, tool_name, parameters, result, status, approval_token, executed_at, created_at
`

type CreateAIToolExecutionParams struct {
	ConversationID uuid.UUID
	FamilyID       uuid.UUID
	UserID         uuid.UUID
	ToolName       string
	Parameters     []byte
	Status         string
	ApprovalToken  *string
}

func (q *Queries) CreateAIToolExecution(ctx context.Context, arg CreateAIToolExecutionParams) (AiToolExecution, error) {
	row := q.db.QueryRow(ctx, createAIToolExecution,
		arg.ConversationID,
		arg.FamilyID,
		arg.UserID,
		arg.ToolName,
		arg.Parameters,
		arg.Status,
		arg.ApprovalToken,
	)
	var i AiToolExecution
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.FamilyID,
		&i.UserID,
		&i.ToolName,
		&i.Parameters,
		&i.Result,
		&i.Status,
		&i.ApprovalToken,
		&i.ExecutedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAIConversationByID = `-- name: GetAIConversationByID :one
SELECT id, family_id, user_id, title, created_at, updated_at FROM ai_conversations
WHERE id = $1 AND family_id = $2
`

type GetAIConversationByIDParams struct {
	ID       uuid.UUID
	FamilyID uuid.UUID
}

func (q *Queries) GetAIConversationByID(ctx context.Context, arg GetAIConversationByIDParams) (AiConversation, error) {
	row := q.db.QueryRow(ctx, getAIConversationByID, arg.ID, arg.FamilyID)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAIToolExecutionByToken = `-- name: GetAIToolExecutionByToken :one
SELECT id, conversation_id, family_id, user_id, tool_name, parameters, result, status, approval_token, executed_at, created_at FROM ai_tool_executions
WHERE approval_token = $1 AND status = 'pending_approval'
`

func (q *Queries) GetAIToolExecutionByToken(ctx context.Context, approvalToken *string) (AiToolExecution, error) {
	row := q.db.QueryRow(ctx, getAIToolExecutionByToken, approvalToken)
	var i AiToolExecution
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.FamilyID,
		&i.UserID,
		&i.ToolName,
		&i.Parameters,
		&i.Result,
		&i.Status,
		&i.ApprovalToken,
		&i.ExecutedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAIConversationsByFamilyID = `-- name: ListAIConversationsByFamilyID :many
SELECT id, family_id, user_id, title, created_at, updated_at FROM ai_conversations
WHERE family_id = $1 AND user_id = $2
ORDER BY updated_at DESC
`

type ListAIConversationsByFamilyIDParams struct {
	FamilyID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) ListAIConversationsByFamilyID(ctx context.Context, arg ListAIConversationsByFamilyIDParams) ([]AiConversation, error) {
	rows, err := q.db.Query(ctx, listAIConversationsByFamilyID, arg.FamilyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiConversation{}
	for rows.Next() {
		var i AiConversation
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIMessagesByConversationID = `-- name: ListAIMessagesByConversationID :many
SELECT id, conversation_id, role, content, tool_calls, tool_call_id, created_at FROM ai_messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAIMessagesByConversationID(ctx context.Context, conversationID uuid.UUID) ([]AiMessage, error) {
	rows, err := q.db.Query(ctx, listAIMessagesByConversationID, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiMessage{}
	for rows.Next() {
		var i AiMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIToolExecutionStatus = `-- name: UpdateAIToolExecutionStatus :one
UPDATE ai_tool_executions
SET status = $2, result = $3, executed_at = now()
WHERE id = $1
RETURNING id, conversation_id, family_id, user_id, tool_name, parameters, result, status, approval_token, executed_at, created_at
`

type UpdateAIToolExecutionStatusParams struct {
	ID     uuid.UUID
	Status string
	Result []byte
}

func (q *Queries) UpdateAIToolExecutionStatus(ctx context.Context, arg UpdateAIToolExecutionStatusParams) (AiToolExecution, error) {
	row := q.db.QueryRow(ctx, updateAIToolExecutionStatus, arg.ID, arg.Status, arg.Result)
	var i AiToolExecution
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.FamilyID,
		&i.UserID,
		&i.ToolName,
		&i.Parameters,
		&i.Result,
		&i.Status,
		&i.ApprovalToken,
		&i.ExecutedAt,
		&i.CreatedAt,
	)
	return i, err
}
