// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (
    family_id, period_year, period_month, total_allocated_cents
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, family_id, period_year, period_month, total_allocated_cents, created_at, updated_at
`

type CreateBudgetParams struct {
	FamilyID            uuid.UUID
	PeriodYear          int16
	PeriodMonth         int16
	TotalAllocatedCents int64
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.FamilyID,
		arg.PeriodYear,
		arg.PeriodMonth,
		arg.TotalAllocatedCents,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.TotalAllocatedCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBudgetItem = `-- name: DeleteBudgetItem :exec
DELETE FROM budget_items
WHERE budget_id = $1 AND category_id = $2
`

type DeleteBudgetItemParams struct {
	BudgetID   uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) DeleteBudgetItem(ctx context.Context, arg DeleteBudgetItemParams) error {
	_, err := q.db.Exec(ctx, deleteBudgetItem, arg.BudgetID, arg.CategoryID)
	return err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, family_id, period_year, period_month, total_allocated_cents, created_at, updated_at FROM budgets
WHERE id = $1 AND family_id = $2
`

type GetBudgetByIDParams struct {
	ID       uuid.UUID
	FamilyID uuid.UUID
}

func (q *Queries) GetBudgetByID(ctx context.Context, arg GetBudgetByIDParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, arg.ID, arg.FamilyID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.TotalAllocatedCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetByPeriod = `-- name: GetBudgetByPeriod :one
SELECT id, family_id, period_year, period_month, total_allocated_cents, created_at, updated_at FROM budgets
WHERE family_id = $1 AND period_year = $2 AND period_month = $3
`

type GetBudgetByPeriodParams struct {
	FamilyID    uuid.UUID
	PeriodYear  int16
	PeriodMonth int16
}

func (q *Queries) GetBudgetByPeriod(ctx context.Context, arg GetBudgetByPeriodParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByPeriod, arg.FamilyID, arg.PeriodYear, arg.PeriodMonth)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.TotalAllocatedCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgetItems = `-- name: ListBudgetItems :many
SELECT bi.id, bi.budget_id, bi.category_id, bi.allocated_amount_cents, bi.rollover_enabled, c.name as category_name, c.icon as category_icon, c.color as category_color, c.kind as category_kind
FROM budget_items bi
JOIN categories c ON c.id = bi.category_id
WHERE bi.budget_id = $1
ORDER BY c.name ASC
`

type ListBudgetItemsRow struct {
	ID                   uuid.UUID
	BudgetID             uuid.UUID
	CategoryID           uuid.UUID
	AllocatedAmountCents int64
	RolloverEnabled      bool
	CategoryName         string
	CategoryIcon         *string
	CategoryColor        *string
	CategoryKind         string
}

func (q *Queries) ListBudgetItems(ctx context.Context, budgetID uuid.UUID) ([]ListBudgetItemsRow, error) {
	rows, err := q.db.Query(ctx, listBudgetItems, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetItemsRow{}
	for rows.Next() {
		var i ListBudgetItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.CategoryID,
			&i.AllocatedAmountCents,
			&i.RolloverEnabled,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.CategoryKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudgetTotalAllocated = `-- name: UpdateBudgetTotalAllocated :one
UPDATE budgets
SET total_allocated_cents = (
    SELECT COALESCE(SUM(allocated_amount_cents), 0)
    FROM budget_items
    WHERE budget_id = $1
),
updated_at = now()
WHERE id = $1 AND family_id = $2
RETURNING id, family_id, period_year, period_month, total_allocated_cents, created_at, updated_at
`

type UpdateBudgetTotalAllocatedParams struct {
	BudgetID uuid.UUID
	FamilyID uuid.UUID
}

func (q *Queries) UpdateBudgetTotalAllocated(ctx context.Context, arg UpdateBudgetTotalAllocatedParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudgetTotalAllocated, arg.BudgetID, arg.FamilyID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.TotalAllocatedCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBudgetItem = `-- name: UpsertBudgetItem :one
INSERT INTO budget_items (
    budget_id, category_id, allocated_amount_cents, rollover_enabled
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (budget_id, category_id) DO UPDATE
SET allocated_amount_cents = EXCLUDED.allocated_amount_cents,
    rollover_enabled = EXCLUDED.rollover_enabled
RETURNING id, budget_id, category_id, allocated_amount_cents, rollover_enabled
`

type UpsertBudgetItemParams struct {
	BudgetID             uuid.UUID
	CategoryID           uuid.UUID
	AllocatedAmountCents int64
	RolloverEnabled      bool
}

func (q *Queries) UpsertBudgetItem(ctx context.Context, arg UpsertBudgetItemParams) (BudgetItem, error) {
	row := q.db.QueryRow(ctx, upsertBudgetItem,
		arg.BudgetID,
		arg.CategoryID,
		arg.AllocatedAmountCents,
		arg.RolloverEnabled,
	)
	var i BudgetItem
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.CategoryID,
		&i.AllocatedAmountCents,
		&i.RolloverEnabled,
	)
	return i, err
}
