// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCreditCard = `-- name: CreateCreditCard :one
INSERT INTO credit_cards (
    account_id, family_id, name, last_four_digits, credit_limit_cents, closing_day, due_day, color
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, account_id, family_id, name, last_four_digits, credit_limit_cents, closing_day, due_day, color, created_at, updated_at
`

type CreateCreditCardParams struct {
	AccountID        uuid.UUID
	FamilyID         uuid.UUID
	Name             string
	LastFourDigits   *string
	CreditLimitCents int64
	ClosingDay       int16
	DueDay           int16
	Color            *string
}

func (q *Queries) CreateCreditCard(ctx context.Context, arg CreateCreditCardParams) (CreditCard, error) {
	row := q.db.QueryRow(ctx, createCreditCard,
		arg.AccountID,
		arg.FamilyID,
		arg.Name,
		arg.LastFourDigits,
		arg.CreditLimitCents,
		arg.ClosingDay,
		arg.DueDay,
		arg.Color,
	)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FamilyID,
		&i.Name,
		&i.LastFourDigits,
		&i.CreditLimitCents,
		&i.ClosingDay,
		&i.DueDay,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreditCardInvoice = `-- name: CreateCreditCardInvoice :one
INSERT INTO credit_card_invoices (
    credit_card_id, family_id, period_year, period_month, closing_date, due_date, total_amount_cents, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (credit_card_id, period_year, period_month) DO UPDATE
SET total_amount_cents = EXCLUDED.total_amount_cents,
    updated_at = now()
RETURNING id, credit_card_id, family_id, period_year, period_month, closing_date, due_date, total_amount_cents, paid_amount_cents, status, created_at, updated_at
`

type CreateCreditCardInvoiceParams struct {
	CreditCardID     uuid.UUID
	FamilyID         uuid.UUID
	PeriodYear       int16
	PeriodMonth      int16
	ClosingDate      time.Time
	DueDate          time.Time
	TotalAmountCents int64
	Status           string
}

func (q *Queries) CreateCreditCardInvoice(ctx context.Context, arg CreateCreditCardInvoiceParams) (CreditCardInvoice, error) {
	row := q.db.QueryRow(ctx, createCreditCardInvoice,
		arg.CreditCardID,
		arg.FamilyID,
		arg.PeriodYear,
		arg.PeriodMonth,
		arg.ClosingDate,
		arg.DueDate,
		arg.TotalAmountCents,
		arg.Status,
	)
	var i CreditCardInvoice
	err := row.Scan(
		&i.ID,
		&i.CreditCardID,
		&i.FamilyID,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.ClosingDate,
		&i.DueDate,
		&i.TotalAmountCents,
		&i.PaidAmountCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditCardByID = `-- name: GetCreditCardByID :one
SELECT id, account_id, family_id, name, last_four_digits, credit_limit_cents, closing_day, due_day, color, created_at, updated_at FROM credit_cards
WHERE id = $1 AND family_id = $2
`

type GetCreditCardByIDParams struct {
	ID       uuid.UUID
	FamilyID uuid.UUID
}

func (q *Queries) GetCreditCardByID(ctx context.Context, arg GetCreditCardByIDParams) (CreditCard, error) {
	row := q.db.QueryRow(ctx, getCreditCardByID, arg.ID, arg.FamilyID)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FamilyID,
		&i.Name,
		&i.LastFourDigits,
		&i.CreditLimitCents,
		&i.ClosingDay,
		&i.DueDay,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditCardInvoiceByPeriod = `-- name: GetCreditCardInvoiceByPeriod :one
SELECT id, credit_card_id, family_id, period_year, period_month, closing_date, due_date, total_amount_cents, paid_amount_cents, status, created_at, updated_at FROM credit_card_invoices
WHERE credit_card_id = $1 AND period_year = $2 AND period_month = $3
`

type GetCreditCardInvoiceByPeriodParams struct {
	CreditCardID uuid.UUID
	PeriodYear   int16
	PeriodMonth  int16
}

func (q *Queries) GetCreditCardInvoiceByPeriod(ctx context.Context, arg GetCreditCardInvoiceByPeriodParams) (CreditCardInvoice, error) {
	row := q.db.QueryRow(ctx, getCreditCardInvoiceByPeriod, arg.CreditCardID, arg.PeriodYear, arg.PeriodMonth)
	var i CreditCardInvoice
	err := row.Scan(
		&i.ID,
		&i.CreditCardID,
		&i.FamilyID,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.ClosingDate,
		&i.DueDate,
		&i.TotalAmountCents,
		&i.PaidAmountCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCreditCardInvoicesByCardID = `-- name: ListCreditCardInvoicesByCardID :many
SELECT id, credit_card_id, family_id, period_year, period_month, closing_date, due_date, total_amount_cents, paid_amount_cents, status, created_at, updated_at FROM credit_card_invoices
WHERE credit_card_id = $1
ORDER BY period_year DESC, period_month DESC
`

func (q *Queries) ListCreditCardInvoicesByCardID(ctx context.Context, creditCardID uuid.UUID) ([]CreditCardInvoice, error) {
	rows, err := q.db.Query(ctx, listCreditCardInvoicesByCardID, creditCardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreditCardInvoice{}
	for rows.Next() {
		var i CreditCardInvoice
		if err := rows.Scan(
			&i.ID,
			&i.CreditCardID,
			&i.FamilyID,
			&i.PeriodYear,
			&i.PeriodMonth,
			&i.ClosingDate,
			&i.DueDate,
			&i.TotalAmountCents,
			&i.PaidAmountCents,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditCardsByFamilyID = `-- name: ListCreditCardsByFamilyID :many
SELECT cc.id, cc.account_id, cc.family_id, cc.name, cc.last_four_digits, cc.credit_limit_cents, cc.closing_day, cc.due_day, cc.color, cc.created_at, cc.updated_at, a.name as account_name
FROM credit_cards cc
JOIN accounts a ON a.id = cc.account_id
WHERE cc.family_id = $1
ORDER BY cc.name ASC
`

type ListCreditCardsByFamilyIDRow struct {
	ID               uuid.UUID
	AccountID        uuid.UUID
	FamilyID         uuid.UUID
	Name             string
	LastFourDigits   *string
	CreditLimitCents int64
	ClosingDay       int16
	DueDay           int16
	Color            *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	AccountName      string
}

func (q *Queries) ListCreditCardsByFamilyID(ctx context.Context, familyID uuid.UUID) ([]ListCreditCardsByFamilyIDRow, error) {
	rows, err := q.db.Query(ctx, listCreditCardsByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCreditCardsByFamilyIDRow{}
	for rows.Next() {
		var i ListCreditCardsByFamilyIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.FamilyID,
			&i.Name,
			&i.LastFourDigits,
			&i.CreditLimitCents,
			&i.ClosingDay,
			&i.DueDay,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
