// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countCategoriesByFamilyID = `-- name: CountCategoriesByFamilyID :one
SELECT count(*) FROM categories
WHERE family_id = $1
`

func (q *Queries) CountCategoriesByFamilyID(ctx context.Context, familyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoriesByFamilyID, familyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    family_id, name, icon, color, kind, parent_id, slug, system_only
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, family_id, name, icon, color, kind, parent_id, created_at, slug, system_only
`

type CreateCategoryParams struct {
	FamilyID   uuid.UUID
	Name       string
	Icon       *string
	Color      *string
	Kind       string
	ParentID   *uuid.UUID
	Slug       *string
	SystemOnly bool
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.FamilyID,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.Kind,
		arg.ParentID,
		arg.Slug,
		arg.SystemOnly,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Kind,
		&i.ParentID,
		&i.CreatedAt,
		&i.Slug,
		&i.SystemOnly,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1 AND family_id = $2
`

type DeleteCategoryParams struct {
	ID       uuid.UUID
	FamilyID uuid.UUID
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.FamilyID)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, family_id, name, icon, color, kind, parent_id, created_at, slug, system_only FROM categories
WHERE id = $1 AND family_id = $2
`

type GetCategoryByIDParams struct {
	ID       uuid.UUID
	FamilyID uuid.UUID
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, arg.ID, arg.FamilyID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Kind,
		&i.ParentID,
		&i.CreatedAt,
		&i.Slug,
		&i.SystemOnly,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, family_id, name, icon, color, kind, parent_id, created_at, slug, system_only FROM categories
WHERE family_id = $1 AND slug = $2
`

type GetCategoryBySlugParams struct {
	FamilyID uuid.UUID
	Slug     *string
}

func (q *Queries) GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, arg.FamilyID, arg.Slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Kind,
		&i.ParentID,
		&i.CreatedAt,
		&i.Slug,
		&i.SystemOnly,
	)
	return i, err
}

const listCategoriesByFamilyID = `-- name: ListCategoriesByFamilyID :many
SELECT id, family_id, name, icon, color, kind, parent_id, created_at, slug, system_only FROM categories
WHERE family_id = $1
ORDER BY name ASC
`

func (q *Queries) ListCategoriesByFamilyID(ctx context.Context, familyID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.Kind,
			&i.ParentID,
			&i.CreatedAt,
			&i.Slug,
			&i.SystemOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleCategoriesByFamilyID = `-- name: ListVisibleCategoriesByFamilyID :many
SELECT id, family_id, name, icon, color, kind, parent_id, created_at, slug, system_only FROM categories
WHERE family_id = $1 AND system_only = FALSE
ORDER BY name ASC
`

func (q *Queries) ListVisibleCategoriesByFamilyID(ctx context.Context, familyID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listVisibleCategoriesByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.Kind,
			&i.ParentID,
			&i.CreatedAt,
			&i.Slug,
			&i.SystemOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $3,
    icon = $4,
    color = $5,
    kind = $6,
    parent_id = $7,
    slug = $8,
    system_only = $9
WHERE id = $1 AND family_id = $2
RETURNING id, family_id, name, icon, color, kind, parent_id, created_at, slug, system_only
`

type UpdateCategoryParams struct {
	ID         uuid.UUID
	FamilyID   uuid.UUID
	Name       string
	Icon       *string
	Color      *string
	Kind       string
	ParentID   *uuid.UUID
	Slug       *string
	SystemOnly bool
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.FamilyID,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.Kind,
		arg.ParentID,
		arg.Slug,
		arg.SystemOnly,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Kind,
		&i.ParentID,
		&i.CreatedAt,
		&i.Slug,
		&i.SystemOnly,
	)
	return i, err
}
