// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: families.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptFamilyInvitation = `-- name: AcceptFamilyInvitation :one
UPDATE family_invitations
SET status = 'accepted'
WHERE id = $1
RETURNING id, family_id, invited_by_user_id, email, role, invite_code, status, expires_at, created_at
`

func (q *Queries) AcceptFamilyInvitation(ctx context.Context, id uuid.UUID) (FamilyInvitation, error) {
	row := q.db.QueryRow(ctx, acceptFamilyInvitation, id)
	var i FamilyInvitation
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.InvitedByUserID,
		&i.Email,
		&i.Role,
		&i.InviteCode,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const addFamilyMember = `-- name: AddFamilyMember :one
INSERT INTO family_members (
    family_id, user_id, role, nickname
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, family_id, user_id, role, nickname, joined_at
`

type AddFamilyMemberParams struct {
	FamilyID uuid.UUID
	UserID   uuid.UUID
	Role     string
	Nickname *string
}

func (q *Queries) AddFamilyMember(ctx context.Context, arg AddFamilyMemberParams) (FamilyMember, error) {
	row := q.db.QueryRow(ctx, addFamilyMember,
		arg.FamilyID,
		arg.UserID,
		arg.Role,
		arg.Nickname,
	)
	var i FamilyMember
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Role,
		&i.Nickname,
		&i.JoinedAt,
	)
	return i, err
}

const createFamily = `-- name: CreateFamily :one
INSERT INTO families (
    name, base_currency
) VALUES (
    $1, $2
)
RETURNING id, name, base_currency, created_at, updated_at
`

type CreateFamilyParams struct {
	Name         string
	BaseCurrency string
}

func (q *Queries) CreateFamily(ctx context.Context, arg CreateFamilyParams) (Family, error) {
	row := q.db.QueryRow(ctx, createFamily, arg.Name, arg.BaseCurrency)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFamilyInvitation = `-- name: CreateFamilyInvitation :one
INSERT INTO family_invitations (
    family_id, invited_by_user_id, email, role, invite_code, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, family_id, invited_by_user_id, email, role, invite_code, status, expires_at, created_at
`

type CreateFamilyInvitationParams struct {
	FamilyID        uuid.UUID
	InvitedByUserID uuid.UUID
	Email           string
	Role            string
	InviteCode      string
	ExpiresAt       time.Time
}

func (q *Queries) CreateFamilyInvitation(ctx context.Context, arg CreateFamilyInvitationParams) (FamilyInvitation, error) {
	row := q.db.QueryRow(ctx, createFamilyInvitation,
		arg.FamilyID,
		arg.InvitedByUserID,
		arg.Email,
		arg.Role,
		arg.InviteCode,
		arg.ExpiresAt,
	)
	var i FamilyInvitation
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.InvitedByUserID,
		&i.Email,
		&i.Role,
		&i.InviteCode,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFamilyMember = `-- name: DeleteFamilyMember :exec
DELETE FROM family_members
WHERE family_id = $1 AND user_id = $2
`

type DeleteFamilyMemberParams struct {
	FamilyID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) DeleteFamilyMember(ctx context.Context, arg DeleteFamilyMemberParams) error {
	_, err := q.db.Exec(ctx, deleteFamilyMember, arg.FamilyID, arg.UserID)
	return err
}

const getFamilyByID = `-- name: GetFamilyByID :one
SELECT id, name, base_currency, created_at, updated_at FROM families
WHERE id = $1
`

func (q *Queries) GetFamilyByID(ctx context.Context, id uuid.UUID) (Family, error) {
	row := q.db.QueryRow(ctx, getFamilyByID, id)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFamilyInvitationByCode = `-- name: GetFamilyInvitationByCode :one
SELECT id, family_id, invited_by_user_id, email, role, invite_code, status, expires_at, created_at FROM family_invitations
WHERE invite_code = $1 AND status = 'pending' AND expires_at > now()
`

func (q *Queries) GetFamilyInvitationByCode(ctx context.Context, inviteCode string) (FamilyInvitation, error) {
	row := q.db.QueryRow(ctx, getFamilyInvitationByCode, inviteCode)
	var i FamilyInvitation
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.InvitedByUserID,
		&i.Email,
		&i.Role,
		&i.InviteCode,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFamilyMemberRole = `-- name: GetFamilyMemberRole :one
SELECT role FROM family_members
WHERE family_id = $1 AND user_id = $2
`

type GetFamilyMemberRoleParams struct {
	FamilyID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetFamilyMemberRole(ctx context.Context, arg GetFamilyMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getFamilyMemberRole, arg.FamilyID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listFamiliesByUserID = `-- name: ListFamiliesByUserID :many
SELECT f.id, f.name, f.base_currency, f.created_at, f.updated_at, fm.role, fm.nickname
FROM families f
JOIN family_members fm ON fm.family_id = f.id
WHERE fm.user_id = $1
ORDER BY f.created_at ASC
`

type ListFamiliesByUserIDRow struct {
	ID           uuid.UUID
	Name         string
	BaseCurrency string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Role         string
	Nickname     *string
}

func (q *Queries) ListFamiliesByUserID(ctx context.Context, userID uuid.UUID) ([]ListFamiliesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listFamiliesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFamiliesByUserIDRow{}
	for rows.Next() {
		var i ListFamiliesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseCurrency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.Nickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFamilyMembers = `-- name: ListFamilyMembers :many
SELECT fm.id, fm.family_id, fm.user_id, fm.role, fm.nickname, fm.joined_at, u.email, u.full_name, u.avatar_url
FROM family_members fm
JOIN users u ON u.id = fm.user_id
WHERE fm.family_id = $1
ORDER BY fm.joined_at ASC
`

type ListFamilyMembersRow struct {
	ID        uuid.UUID
	FamilyID  uuid.UUID
	UserID    uuid.UUID
	Role      string
	Nickname  *string
	JoinedAt  time.Time
	Email     string
	FullName  string
	AvatarUrl *string
}

func (q *Queries) ListFamilyMembers(ctx context.Context, familyID uuid.UUID) ([]ListFamilyMembersRow, error) {
	rows, err := q.db.Query(ctx, listFamilyMembers, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFamilyMembersRow{}
	for rows.Next() {
		var i ListFamilyMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.UserID,
			&i.Role,
			&i.Nickname,
			&i.JoinedAt,
			&i.Email,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFamilyMemberRole = `-- name: UpdateFamilyMemberRole :one
UPDATE family_members
SET role = $3, nickname = $4
WHERE family_id = $1 AND user_id = $2
RETURNING id, family_id, user_id, role, nickname, joined_at
`

type UpdateFamilyMemberRoleParams struct {
	FamilyID uuid.UUID
	UserID   uuid.UUID
	Role     string
	Nickname *string
}

func (q *Queries) UpdateFamilyMemberRole(ctx context.Context, arg UpdateFamilyMemberRoleParams) (FamilyMember, error) {
	row := q.db.QueryRow(ctx, updateFamilyMemberRole,
		arg.FamilyID,
		arg.UserID,
		arg.Role,
		arg.Nickname,
	)
	var i FamilyMember
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Role,
		&i.Nickname,
		&i.JoinedAt,
	)
	return i, err
}
