// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investments.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvestmentOrder = `-- name: CreateInvestmentOrder :one
INSERT INTO investment_orders (
    family_id, account_id, asset_id, user_id, order_type, quantity, unit_price_cents, fees_cents, total_amount_cents, executed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, family_id, account_id, asset_id, user_id, order_type, quantity, unit_price_cents, fees_cents, total_amount_cents, executed_at, created_at
`

type CreateInvestmentOrderParams struct {
	FamilyID         uuid.UUID
	AccountID        uuid.UUID
	AssetID          uuid.UUID
	UserID           uuid.UUID
	OrderType        string
	Quantity         pgtype.Numeric
	UnitPriceCents   int64
	FeesCents        int64
	TotalAmountCents int64
	ExecutedAt       time.Time
}

func (q *Queries) CreateInvestmentOrder(ctx context.Context, arg CreateInvestmentOrderParams) (InvestmentOrder, error) {
	row := q.db.QueryRow(ctx, createInvestmentOrder,
		arg.FamilyID,
		arg.AccountID,
		arg.AssetID,
		arg.UserID,
		arg.OrderType,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.FeesCents,
		arg.TotalAmountCents,
		arg.ExecutedAt,
	)
	var i InvestmentOrder
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AccountID,
		&i.AssetID,
		&i.UserID,
		&i.OrderType,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.FeesCents,
		&i.TotalAmountCents,
		&i.ExecutedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetByTicker = `-- name: GetAssetByTicker :one
SELECT id, ticker, name, asset_class, currency, sector, is_active, created_at, updated_at FROM investment_assets
WHERE ticker = $1
`

func (q *Queries) GetAssetByTicker(ctx context.Context, ticker string) (InvestmentAsset, error) {
	row := q.db.QueryRow(ctx, getAssetByTicker, ticker)
	var i InvestmentAsset
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Name,
		&i.AssetClass,
		&i.Currency,
		&i.Sector,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvestmentThesisByFamilyID = `-- name: GetInvestmentThesisByFamilyID :one
SELECT id, family_id, risk_profile, target_allocations, rebalancing_tolerance_pct, notes, updated_at FROM investment_theses
WHERE family_id = $1
`

func (q *Queries) GetInvestmentThesisByFamilyID(ctx context.Context, familyID uuid.UUID) (InvestmentThesis, error) {
	row := q.db.QueryRow(ctx, getInvestmentThesisByFamilyID, familyID)
	var i InvestmentThesis
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.RiskProfile,
		&i.TargetAllocations,
		&i.RebalancingTolerancePct,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, ticker, name, asset_class, currency, sector, is_active, created_at, updated_at FROM investment_assets
WHERE is_active = TRUE
ORDER BY ticker ASC
`

func (q *Queries) ListAssets(ctx context.Context) ([]InvestmentAsset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvestmentAsset{}
	for rows.Next() {
		var i InvestmentAsset
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.Name,
			&i.AssetClass,
			&i.Currency,
			&i.Sector,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentPositionsByFamilyID = `-- name: ListInvestmentPositionsByFamilyID :many
SELECT ip.id, ip.family_id, ip.account_id, ip.asset_id, ip.quantity, ip.average_price_cents, ip.total_cost_cents, ip.accumulated_dividends_cents, ip.updated_at, ia.ticker, ia.name as asset_name, ia.asset_class, ia.currency as asset_currency, a.name as account_name
FROM investment_positions ip
JOIN investment_assets ia ON ia.id = ip.asset_id
JOIN accounts a ON a.id = ip.account_id
WHERE ip.family_id = $1 AND ip.quantity > 0
ORDER BY ia.ticker ASC
`

type ListInvestmentPositionsByFamilyIDRow struct {
	ID                        uuid.UUID
	FamilyID                  uuid.UUID
	AccountID                 uuid.UUID
	AssetID                   uuid.UUID
	Quantity                  pgtype.Numeric
	AveragePriceCents         int64
	TotalCostCents            int64
	AccumulatedDividendsCents int64
	UpdatedAt                 time.Time
	Ticker                    string
	AssetName                 string
	AssetClass                string
	AssetCurrency             string
	AccountName               string
}

func (q *Queries) ListInvestmentPositionsByFamilyID(ctx context.Context, familyID uuid.UUID) ([]ListInvestmentPositionsByFamilyIDRow, error) {
	rows, err := q.db.Query(ctx, listInvestmentPositionsByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvestmentPositionsByFamilyIDRow{}
	for rows.Next() {
		var i ListInvestmentPositionsByFamilyIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AccountID,
			&i.AssetID,
			&i.Quantity,
			&i.AveragePriceCents,
			&i.TotalCostCents,
			&i.AccumulatedDividendsCents,
			&i.UpdatedAt,
			&i.Ticker,
			&i.AssetName,
			&i.AssetClass,
			&i.AssetCurrency,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAsset = `-- name: UpsertAsset :one
INSERT INTO investment_assets (
    ticker, name, asset_class, currency, sector
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (ticker) DO UPDATE
SET name = EXCLUDED.name,
    sector = EXCLUDED.sector,
    updated_at = now()
RETURNING id, ticker, name, asset_class, currency, sector, is_active, created_at, updated_at
`

type UpsertAssetParams struct {
	Ticker     string
	Name       string
	AssetClass string
	Currency   string
	Sector     *string
}

func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) (InvestmentAsset, error) {
	row := q.db.QueryRow(ctx, upsertAsset,
		arg.Ticker,
		arg.Name,
		arg.AssetClass,
		arg.Currency,
		arg.Sector,
	)
	var i InvestmentAsset
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Name,
		&i.AssetClass,
		&i.Currency,
		&i.Sector,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInvestmentPosition = `-- name: UpsertInvestmentPosition :one
INSERT INTO investment_positions (
    family_id, account_id, asset_id, quantity, average_price_cents, total_cost_cents, accumulated_dividends_cents
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (account_id, asset_id) DO UPDATE
SET quantity = EXCLUDED.quantity,
    average_price_cents = EXCLUDED.average_price_cents,
    total_cost_cents = EXCLUDED.total_cost_cents,
    accumulated_dividends_cents = EXCLUDED.accumulated_dividends_cents,
    updated_at = now()
RETURNING id, family_id, account_id, asset_id, quantity, average_price_cents, total_cost_cents, accumulated_dividends_cents, updated_at
`

type UpsertInvestmentPositionParams struct {
	FamilyID                  uuid.UUID
	AccountID                 uuid.UUID
	AssetID                   uuid.UUID
	Quantity                  pgtype.Numeric
	AveragePriceCents         int64
	TotalCostCents            int64
	AccumulatedDividendsCents int64
}

func (q *Queries) UpsertInvestmentPosition(ctx context.Context, arg UpsertInvestmentPositionParams) (InvestmentPosition, error) {
	row := q.db.QueryRow(ctx, upsertInvestmentPosition,
		arg.FamilyID,
		arg.AccountID,
		arg.AssetID,
		arg.Quantity,
		arg.AveragePriceCents,
		arg.TotalCostCents,
		arg.AccumulatedDividendsCents,
	)
	var i InvestmentPosition
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AccountID,
		&i.AssetID,
		&i.Quantity,
		&i.AveragePriceCents,
		&i.TotalCostCents,
		&i.AccumulatedDividendsCents,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInvestmentThesis = `-- name: UpsertInvestmentThesis :one
INSERT INTO investment_theses (
    family_id, risk_profile, target_allocations, rebalancing_tolerance_pct, notes
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (family_id) DO UPDATE
SET risk_profile = EXCLUDED.risk_profile,
    target_allocations = EXCLUDED.target_allocations,
    rebalancing_tolerance_pct = EXCLUDED.rebalancing_tolerance_pct,
    notes = EXCLUDED.notes,
    updated_at = now()
RETURNING id, family_id, risk_profile, target_allocations, rebalancing_tolerance_pct, notes, updated_at
`

type UpsertInvestmentThesisParams struct {
	FamilyID                uuid.UUID
	RiskProfile             string
	TargetAllocations       []byte
	RebalancingTolerancePct pgtype.Numeric
	Notes                   *string
}

func (q *Queries) UpsertInvestmentThesis(ctx context.Context, arg UpsertInvestmentThesisParams) (InvestmentThesis, error) {
	row := q.db.QueryRow(ctx, upsertInvestmentThesis,
		arg.FamilyID,
		arg.RiskProfile,
		arg.TargetAllocations,
		arg.RebalancingTolerancePct,
		arg.Notes,
	)
	var i InvestmentThesis
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.RiskProfile,
		&i.TargetAllocations,
		&i.RebalancingTolerancePct,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}
