// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                  uuid.UUID
	FamilyID            uuid.UUID
	OwnerUserID         uuid.UUID
	Name                string
	Kind                string
	Visibility          string
	Currency            string
	InitialBalanceCents int64
	CurrentBalanceCents int64
	Color               *string
	IsArchived          bool
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type AiConversation struct {
	ID        uuid.UUID
	FamilyID  uuid.UUID
	UserID    uuid.UUID
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AiMessage struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Role           string
	Content        *string
	ToolCalls      []byte
	ToolCallID     *string
	CreatedAt      time.Time
}

type AiToolExecution struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	FamilyID       uuid.UUID
	UserID         uuid.UUID
	ToolName       string
	Parameters     []byte
	Result         []byte
	Status         string
	ApprovalToken  *string
	ExecutedAt     *time.Time
	CreatedAt      time.Time
}

type AssetQuote struct {
	ID         uuid.UUID
	AssetID    uuid.UUID
	PriceCents int64
	ChangePct  pgtype.Numeric
	AsOf       time.Time
	CreatedAt  time.Time
}

type AuthIdentity struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	Email          *string
	CreatedAt      time.Time
}

type Budget struct {
	ID                  uuid.UUID
	FamilyID            uuid.UUID
	PeriodYear          int16
	PeriodMonth         int16
	TotalAllocatedCents int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type BudgetItem struct {
	ID                   uuid.UUID
	BudgetID             uuid.UUID
	CategoryID           uuid.UUID
	AllocatedAmountCents int64
	RolloverEnabled      bool
}

type Category struct {
	ID        uuid.UUID
	FamilyID  uuid.UUID
	Name      string
	Icon      *string
	Color     *string
	Kind      string
	ParentID  *uuid.UUID
	CreatedAt time.Time
}

type CreditCard struct {
	ID               uuid.UUID
	AccountID        uuid.UUID
	FamilyID         uuid.UUID
	Name             string
	LastFourDigits   *string
	CreditLimitCents int64
	ClosingDay       int16
	DueDay           int16
	Color            *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type CreditCardInvoice struct {
	ID               uuid.UUID
	CreditCardID     uuid.UUID
	FamilyID         uuid.UUID
	PeriodYear       int16
	PeriodMonth      int16
	ClosingDate      time.Time
	DueDate          time.Time
	TotalAmountCents int64
	PaidAmountCents  int64
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Family struct {
	ID           uuid.UUID
	Name         string
	BaseCurrency string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type FamilyInvitation struct {
	ID              uuid.UUID
	FamilyID        uuid.UUID
	InvitedByUserID uuid.UUID
	Email           string
	Role            string
	InviteCode      string
	Status          string
	ExpiresAt       time.Time
	CreatedAt       time.Time
}

type FamilyMember struct {
	ID       uuid.UUID
	FamilyID uuid.UUID
	UserID   uuid.UUID
	Role     string
	Nickname *string
	JoinedAt time.Time
}

type InvestmentAsset struct {
	ID         uuid.UUID
	Ticker     string
	Name       string
	AssetClass string
	Currency   string
	Sector     *string
	IsActive   bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type InvestmentOrder struct {
	ID               uuid.UUID
	FamilyID         uuid.UUID
	AccountID        uuid.UUID
	AssetID          uuid.UUID
	UserID           uuid.UUID
	OrderType        string
	Quantity         pgtype.Numeric
	UnitPriceCents   int64
	FeesCents        int64
	TotalAmountCents int64
	ExecutedAt       time.Time
	CreatedAt        time.Time
}

type InvestmentPosition struct {
	ID                        uuid.UUID
	FamilyID                  uuid.UUID
	AccountID                 uuid.UUID
	AssetID                   uuid.UUID
	Quantity                  pgtype.Numeric
	AveragePriceCents         int64
	TotalCostCents            int64
	AccumulatedDividendsCents int64
	UpdatedAt                 time.Time
}

type InvestmentThesis struct {
	ID                      uuid.UUID
	FamilyID                uuid.UUID
	RiskProfile             string
	TargetAllocations       []byte
	RebalancingTolerancePct pgtype.Numeric
	Notes                   *string
	UpdatedAt               time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type Transaction struct {
	ID                  uuid.UUID
	FamilyID            uuid.UUID
	AccountID           uuid.UUID
	CategoryID          *uuid.UUID
	CreatedByUserID     uuid.UUID
	TargetUserID        *uuid.UUID
	Kind                string
	AmountCents         int64
	Description         string
	TransactedAt        time.Time
	Status              string
	CreditCardInvoiceID *uuid.UUID
	InstallmentNumber   *int16
	InstallmentTotal    *int16
	InstallmentGroupID  *uuid.UUID
	Tags                []string
	Notes               *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	FullName     string
	PasswordHash *string
	AvatarUrl    *string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserDevice struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Platform    string
	ApnsToken   *string
	FcmToken    *string
	AppVersion  *string
	DeviceModel *string
	LastSeenAt  time.Time
	CreatedAt   time.Time
}
