// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptFamilyInvitation(ctx context.Context, id uuid.UUID) (FamilyInvitation, error)
	AddFamilyMember(ctx context.Context, arg AddFamilyMemberParams) (FamilyMember, error)
	ArchiveAccount(ctx context.Context, arg ArchiveAccountParams) error
	CountCategoriesByFamilyID(ctx context.Context, familyID uuid.UUID) (int64, error)
	CreateAIConversation(ctx context.Context, arg CreateAIConversationParams) (AiConversation, error)
	CreateAIMessage(ctx context.Context, arg CreateAIMessageParams) (AiMessage, error)
	CreateAIToolExecution(ctx context.Context, arg CreateAIToolExecutionParams) (AiToolExecution, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCreditCard(ctx context.Context, arg CreateCreditCardParams) (CreditCard, error)
	CreateCreditCardInvoice(ctx context.Context, arg CreateCreditCardInvoiceParams) (CreditCardInvoice, error)
	CreateFamily(ctx context.Context, arg CreateFamilyParams) (Family, error)
	CreateFamilyInvitation(ctx context.Context, arg CreateFamilyInvitationParams) (FamilyInvitation, error)
	CreateInvestmentOrder(ctx context.Context, arg CreateInvestmentOrderParams) (InvestmentOrder, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBudgetItem(ctx context.Context, arg DeleteBudgetItemParams) error
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteFamilyMember(ctx context.Context, arg DeleteFamilyMemberParams) error
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error
	GetAIConversationByID(ctx context.Context, arg GetAIConversationByIDParams) (AiConversation, error)
	GetAIToolExecutionByToken(ctx context.Context, approvalToken *string) (AiToolExecution, error)
	GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error)
	GetAssetByTicker(ctx context.Context, ticker string) (InvestmentAsset, error)
	GetAuthIdentity(ctx context.Context, arg GetAuthIdentityParams) (AuthIdentity, error)
	GetBudgetByID(ctx context.Context, arg GetBudgetByIDParams) (Budget, error)
	GetBudgetByPeriod(ctx context.Context, arg GetBudgetByPeriodParams) (Budget, error)
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error)
	GetCategorySpendingForPeriod(ctx context.Context, arg GetCategorySpendingForPeriodParams) ([]GetCategorySpendingForPeriodRow, error)
	GetCreditCardByAccountID(ctx context.Context, arg GetCreditCardByAccountIDParams) (CreditCard, error)
	GetCreditCardByID(ctx context.Context, arg GetCreditCardByIDParams) (CreditCard, error)
	GetCreditCardInvoiceByID(ctx context.Context, arg GetCreditCardInvoiceByIDParams) (CreditCardInvoice, error)
	GetCreditCardInvoiceByPeriod(ctx context.Context, arg GetCreditCardInvoiceByPeriodParams) (CreditCardInvoice, error)
	GetFamilyByID(ctx context.Context, id uuid.UUID) (Family, error)
	GetFamilyInvitationByCode(ctx context.Context, inviteCode string) (FamilyInvitation, error)
	GetFamilyMemberRole(ctx context.Context, arg GetFamilyMemberRoleParams) (string, error)
	GetInvestmentThesisByFamilyID(ctx context.Context, familyID uuid.UUID) (InvestmentThesis, error)
	GetMonthlyCashFlowTotals(ctx context.Context, arg GetMonthlyCashFlowTotalsParams) (GetMonthlyCashFlowTotalsRow, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (GetTransactionByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAIConversationsByFamilyID(ctx context.Context, arg ListAIConversationsByFamilyIDParams) ([]AiConversation, error)
	ListAIMessagesByConversationID(ctx context.Context, conversationID uuid.UUID) ([]AiMessage, error)
	ListAccountsByFamilyID(ctx context.Context, familyID uuid.UUID) ([]ListAccountsByFamilyIDRow, error)
	ListAssets(ctx context.Context) ([]InvestmentAsset, error)
	ListBudgetItems(ctx context.Context, budgetID uuid.UUID) ([]ListBudgetItemsRow, error)
	ListCategoriesByFamilyID(ctx context.Context, familyID uuid.UUID) ([]Category, error)
	ListCreditCardInvoicesByCardID(ctx context.Context, creditCardID uuid.UUID) ([]CreditCardInvoice, error)
	ListCreditCardsByFamilyID(ctx context.Context, familyID uuid.UUID) ([]ListCreditCardsByFamilyIDRow, error)
	ListFamiliesByUserID(ctx context.Context, userID uuid.UUID) ([]ListFamiliesByUserIDRow, error)
	ListFamilyMembers(ctx context.Context, familyID uuid.UUID) ([]ListFamilyMembersRow, error)
	ListFutureInstallmentsByCardID(ctx context.Context, arg ListFutureInstallmentsByCardIDParams) ([]ListFutureInstallmentsByCardIDRow, error)
	ListInvestmentPositionsByFamilyID(ctx context.Context, familyID uuid.UUID) ([]ListInvestmentPositionsByFamilyIDRow, error)
	ListTransactionsByFamilyID(ctx context.Context, arg ListTransactionsByFamilyIDParams) ([]ListTransactionsByFamilyIDRow, error)
	ListTransactionsByFamilyIDWithFilters(ctx context.Context, arg ListTransactionsByFamilyIDWithFiltersParams) ([]ListTransactionsByFamilyIDWithFiltersRow, error)
	ListTransactionsByInstallmentGroupID(ctx context.Context, arg ListTransactionsByInstallmentGroupIDParams) ([]ListTransactionsByInstallmentGroupIDRow, error)
	ListTransactionsByInvoiceID(ctx context.Context, arg ListTransactionsByInvoiceIDParams) ([]ListTransactionsByInvoiceIDRow, error)
	RegisterUserDevice(ctx context.Context, arg RegisterUserDeviceParams) (UserDevice, error)
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	UpdateAIToolExecutionStatus(ctx context.Context, arg UpdateAIToolExecutionStatusParams) (AiToolExecution, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateBudgetTotalAllocated(ctx context.Context, arg UpdateBudgetTotalAllocatedParams) (Budget, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCreditCardInvoicePaid(ctx context.Context, arg UpdateCreditCardInvoicePaidParams) (CreditCardInvoice, error)
	UpdateCreditCardInvoiceTotals(ctx context.Context, arg UpdateCreditCardInvoiceTotalsParams) (CreditCardInvoice, error)
	UpdateFamilyMemberRole(ctx context.Context, arg UpdateFamilyMemberRoleParams) (FamilyMember, error)
	UpdateTransactionInvoiceAndAmount(ctx context.Context, arg UpdateTransactionInvoiceAndAmountParams) (Transaction, error)
	UpsertAsset(ctx context.Context, arg UpsertAssetParams) (InvestmentAsset, error)
	UpsertBudgetItem(ctx context.Context, arg UpsertBudgetItemParams) (BudgetItem, error)
	UpsertInvestmentPosition(ctx context.Context, arg UpsertInvestmentPositionParams) (InvestmentPosition, error)
	UpsertInvestmentThesis(ctx context.Context, arg UpsertInvestmentThesisParams) (InvestmentThesis, error)
}

var _ Querier = (*Queries)(nil)
