// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    family_id, account_id, category_id, created_by_user_id, target_user_id,
    kind, amount_cents, description, transacted_at, status,
    credit_card_invoice_id, installment_number, installment_total, installment_group_id,
    tags, notes
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16
)
RETURNING id, family_id, account_id, category_id, created_by_user_id, target_user_id, kind, amount_cents, description, transacted_at, status, credit_card_invoice_id, installment_number, installment_total, installment_group_id, tags, notes, created_at, updated_at
`

type CreateTransactionParams struct {
	FamilyID            uuid.UUID
	AccountID           uuid.UUID
	CategoryID          *uuid.UUID
	CreatedByUserID     uuid.UUID
	TargetUserID        *uuid.UUID
	Kind                string
	AmountCents         int64
	Description         string
	TransactedAt        time.Time
	Status              string
	CreditCardInvoiceID *uuid.UUID
	InstallmentNumber   *int16
	InstallmentTotal    *int16
	InstallmentGroupID  *uuid.UUID
	Tags                []string
	Notes               *string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.FamilyID,
		arg.AccountID,
		arg.CategoryID,
		arg.CreatedByUserID,
		arg.TargetUserID,
		arg.Kind,
		arg.AmountCents,
		arg.Description,
		arg.TransactedAt,
		arg.Status,
		arg.CreditCardInvoiceID,
		arg.InstallmentNumber,
		arg.InstallmentTotal,
		arg.InstallmentGroupID,
		arg.Tags,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AccountID,
		&i.CategoryID,
		&i.CreatedByUserID,
		&i.TargetUserID,
		&i.Kind,
		&i.AmountCents,
		&i.Description,
		&i.TransactedAt,
		&i.Status,
		&i.CreditCardInvoiceID,
		&i.InstallmentNumber,
		&i.InstallmentTotal,
		&i.InstallmentGroupID,
		&i.Tags,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1 AND family_id = $2
`

type DeleteTransactionParams struct {
	ID       uuid.UUID
	FamilyID uuid.UUID
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.FamilyID)
	return err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT t.id, t.family_id, t.account_id, t.category_id, t.created_by_user_id, t.target_user_id, t.kind, t.amount_cents, t.description, t.transacted_at, t.status, t.credit_card_invoice_id, t.installment_number, t.installment_total, t.installment_group_id, t.tags, t.notes, t.created_at, t.updated_at, c.name as category_name, a.name as account_name, u.full_name as author_name
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
JOIN accounts a ON a.id = t.account_id
JOIN users u ON u.id = t.created_by_user_id
WHERE t.id = $1 AND t.family_id = $2
`

type GetTransactionByIDParams struct {
	ID       uuid.UUID
	FamilyID uuid.UUID
}

type GetTransactionByIDRow struct {
	ID                  uuid.UUID
	FamilyID            uuid.UUID
	AccountID           uuid.UUID
	CategoryID          *uuid.UUID
	CreatedByUserID     uuid.UUID
	TargetUserID        *uuid.UUID
	Kind                string
	AmountCents         int64
	Description         string
	TransactedAt        time.Time
	Status              string
	CreditCardInvoiceID *uuid.UUID
	InstallmentNumber   *int16
	InstallmentTotal    *int16
	InstallmentGroupID  *uuid.UUID
	Tags                []string
	Notes               *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	CategoryName        *string
	AccountName         string
	AuthorName          string
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.ID, arg.FamilyID)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AccountID,
		&i.CategoryID,
		&i.CreatedByUserID,
		&i.TargetUserID,
		&i.Kind,
		&i.AmountCents,
		&i.Description,
		&i.TransactedAt,
		&i.Status,
		&i.CreditCardInvoiceID,
		&i.InstallmentNumber,
		&i.InstallmentTotal,
		&i.InstallmentGroupID,
		&i.Tags,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.AccountName,
		&i.AuthorName,
	)
	return i, err
}

const listTransactionsByFamilyID = `-- name: ListTransactionsByFamilyID :many
SELECT t.id, t.family_id, t.account_id, t.category_id, t.created_by_user_id, t.target_user_id, t.kind, t.amount_cents, t.description, t.transacted_at, t.status, t.credit_card_invoice_id, t.installment_number, t.installment_total, t.installment_group_id, t.tags, t.notes, t.created_at, t.updated_at, c.name as category_name, c.icon as category_icon, c.color as category_color, a.name as account_name
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
JOIN accounts a ON a.id = t.account_id
WHERE t.family_id = $1
  AND ($2::uuid IS NULL OR t.account_id = $2)
  AND ($3::uuid IS NULL OR t.category_id = $3)
  AND ($4::timestamptz IS NULL OR t.transacted_at >= $4)
  AND ($5::timestamptz IS NULL OR t.transacted_at <= $5)
ORDER BY t.transacted_at DESC, t.created_at DESC
LIMIT $6 OFFSET $7
`

type ListTransactionsByFamilyIDParams struct {
	FamilyID uuid.UUID
	Column2  uuid.UUID
	Column3  uuid.UUID
	Column4  time.Time
	Column5  time.Time
	Limit    int32
	Offset   int32
}

type ListTransactionsByFamilyIDRow struct {
	ID                  uuid.UUID
	FamilyID            uuid.UUID
	AccountID           uuid.UUID
	CategoryID          *uuid.UUID
	CreatedByUserID     uuid.UUID
	TargetUserID        *uuid.UUID
	Kind                string
	AmountCents         int64
	Description         string
	TransactedAt        time.Time
	Status              string
	CreditCardInvoiceID *uuid.UUID
	InstallmentNumber   *int16
	InstallmentTotal    *int16
	InstallmentGroupID  *uuid.UUID
	Tags                []string
	Notes               *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	CategoryName        *string
	CategoryIcon        *string
	CategoryColor       *string
	AccountName         string
}

func (q *Queries) ListTransactionsByFamilyID(ctx context.Context, arg ListTransactionsByFamilyIDParams) ([]ListTransactionsByFamilyIDRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByFamilyID,
		arg.FamilyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByFamilyIDRow{}
	for rows.Next() {
		var i ListTransactionsByFamilyIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AccountID,
			&i.CategoryID,
			&i.CreatedByUserID,
			&i.TargetUserID,
			&i.Kind,
			&i.AmountCents,
			&i.Description,
			&i.TransactedAt,
			&i.Status,
			&i.CreditCardInvoiceID,
			&i.InstallmentNumber,
			&i.InstallmentTotal,
			&i.InstallmentGroupID,
			&i.Tags,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
