// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAuthIdentity = `-- name: CreateAuthIdentity :one
INSERT INTO auth_identities (
    user_id, provider, provider_user_id, email
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, provider, provider_user_id, email, created_at
`

type CreateAuthIdentityParams struct {
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	Email          *string
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id, token_hash, expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, full_name, password_hash, avatar_url
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, email, full_name, password_hash, avatar_url, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	FullName     string
	PasswordHash *string
	AvatarUrl    *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthIdentity = `-- name: GetAuthIdentity :one
SELECT id, user_id, provider, provider_user_id, email, created_at FROM auth_identities
WHERE provider = $1 AND provider_user_id = $2
`

type GetAuthIdentityParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetAuthIdentity(ctx context.Context, arg GetAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getAuthIdentity, arg.Provider, arg.ProviderUserID)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, password_hash, avatar_url, is_active, created_at, updated_at FROM users
WHERE email = $1 AND is_active = TRUE
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, full_name, password_hash, avatar_url, is_active, created_at, updated_at FROM users
WHERE id = $1 AND is_active = TRUE
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerUserDevice = `-- name: RegisterUserDevice :one
INSERT INTO user_devices (
    user_id, platform, apns_token, fcm_token, app_version, device_model
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id, apns_token) DO UPDATE
SET platform = EXCLUDED.platform,
    fcm_token = EXCLUDED.fcm_token,
    app_version = EXCLUDED.app_version,
    device_model = EXCLUDED.device_model,
    last_seen_at = now()
RETURNING id, user_id, platform, apns_token, fcm_token, app_version, device_model, last_seen_at, created_at
`

type RegisterUserDeviceParams struct {
	UserID      uuid.UUID
	Platform    string
	ApnsToken   *string
	FcmToken    *string
	AppVersion  *string
	DeviceModel *string
}

func (q *Queries) RegisterUserDevice(ctx context.Context, arg RegisterUserDeviceParams) (UserDevice, error) {
	row := q.db.QueryRow(ctx, registerUserDevice,
		arg.UserID,
		arg.Platform,
		arg.ApnsToken,
		arg.FcmToken,
		arg.AppVersion,
		arg.DeviceModel,
	)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.ApnsToken,
		&i.FcmToken,
		&i.AppVersion,
		&i.DeviceModel,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}
